name: Generate Consolidated RSS

on:
  schedule:
    # Once every hour; adjust as needed
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedgen requests

      - name: Generate RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: yoohoo-plugins
        run: python scripts/generate_feed.py

      - name: Commit & push feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases.xml
          git commit -m "chore: update releases feed" || echo "No changes"
          git push origin HEAD:gh-pages
