name: Generate Consolidated RSS (via Atom feeds)

on:
  schedule:
    # Every hour; adjust as needed
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install feedgen feedparser requests

      - name: Generate RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: yoohoo-plugins
        run: python3 scripts/generate_feed.py

      - name: Commit & push feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          git add releases.xml
          git commit -m "chore: update releases feed" || echo "No changes to commit"
          git push -f origin gh-pages